### ISSUE TITLE
AdapterSpy : should continue browsing children

### ISSUE THREAD

**Issue by opcoach** [lacherp/org.eclipse.e4.tools#10]
When a child is displayed, it should propose to continue to expand nodes if this child can be transformed into/from another type.

**Comment by lacherp** [comment]
I'm not sure I understood the point,
For example, if a parent does not have a child, do you want to see an arrow in the tree to close/open the child?

tree open on the first level : 
v - parent 
   > - child 1 ( with no child)
   > -child 2 ( with child )

tree open on the second level 
v - parent 
   v - child 1 
   v - child 2 
             > child 2.1

**Comment by opcoach** [comment]
I meant, if for a parent there are 3 types and for instance only Type 2 has children....

At first level we will have : 

- parent
   - Type1
   - Type2 (must be expandable)
   - Type3
- Type2
   - ChildForType2
   - AnotherChildForType2


If all nodes are expanded we will redisplay the type2 children to continue navigation and avoid to go back in root nodes and find Type 2... : 

- parent
   - Type1
   - Type2 (expanded, display again types displayed for root node)
         - ChildForType2
         - AnotherChildForType2
   - Type3
- Type2
   - ChildForType2
   - AnotherChildForType2

**Comment by lacherp** [comment]
please check again, it's to be ok for me

**Comment by opcoach** [comment]
It is good like this ! :) I close the issue.
