### ISSUE TITLE
AdapterSpy : add a tooltip on each node in the tree

### ISSUE THREAD

**Issue by opcoach** [lacherp/org.eclipse.e4.tools#11]
For column 1 

for root node : 
 'expand this node to know the types in which XXX can be adapted' for (source type mode).    XXX is the current type 
 'expand this node to know the types that can be adapted to XXX'   (destination type mode).    

for children node : 
  'XXX can be transformed to YYY using ZZZ adapter factory'
 of 'YYY can be obtained from XXX using ZZZ adapter factory'

For AdapterFactory column : 
    'ZZZ adapter factory can transform XXX to YYY'   (and if it is possible to YYY1, YYY2, YYY3, YYY4)

Each node should be explained with a tooltip with a text containing the source/destination/factory's types used at this level

**Comment by lacherp** [comment]
i'm not sure what you want for (and if it is possible to YYY1, YYY2, YYY3, YYY4) 
see CI 6aa5221

**Comment by opcoach** [comment]
General remark on tooltip : 

- Try to change the background color to yellow for instance ? Grey is less readable when the table displays white and grey lines...
- If you can find it, display the class names in bold and remove double quotes "IFile" becomes **IFile**


First level tooltip (for source and destination) -> text OK, start with an uppercase (expand this node -> Expand this node...)

For the children : 
 
-  in Destination type mode,  the text starts with 'of', should remove it
-   in Source type mode,  change **_using_** by **_by the_** because we never use directly the adapter factory explicitly but we ask the Adapter to adapt...  and **_transformed_** to **_adapted_** so text : 'IFileEditorInput can be transformed to IModelElement using the FileEditorInputAdapterFactory could be changed to "IFileEditorInput can be **_adapted to_** IModelElement **_by the_** the FileEditorInputAdapterFactory".  Add an '\n' before **_by the_** to put the text on 2 lines

**Comment by lacherp** [comment]
i put a sample video to show tooltip design.

its ok for you ?

https://user-images.githubusercontent.com/58602053/111898532-ecbafd80-8a26-11eb-8f0a-029a4f7c5bf7.mp4

**Comment by opcoach** [comment]
Sounds good :)  You can close it
