### ISSUE TITLE
AdapterSpy : remove duplicates in first column

### ISSUE THREAD

**Issue by opcoach** [lacherp/org.eclipse.e4.tools#2]
Remove duplicates in the tree of destination types or source types. 

For instance iResource or IProject are displayed many times while it would be better to display it once, and then get all children with one click only.

**Comment by lacherp** [comment]
duplicate items are displayed only once when the reduceType box is checked. 
Should I remove the checkbox and enable the default functionality ?

**Comment by opcoach** [comment]
By default there should be no duplicated items...  Don't understand what this checkbox does exactly ... 

We need to have only once the types on each level ( but they can appear again on different levels (see issue #10))

**Comment by opcoach** [comment]
Filter is ok now even when we switch from 'Destination first' to "Source type first"... 
Duplicates are not displayed -> OK
Close
