### ISSUE TITLE
AdapterSpy : Change icon for source type

### ISSUE THREAD

**Issue by opcoach** [lacherp/org.eclipse.e4.tools#6]
While the destination type icon is readable, I don't really like the round arrow for the source type. 

May be the class icon would be more intuitive : 

platform:/plugin/org.eclipse.wst.jsdt.ui/icons/full/elcl16/class_obj.gif

**Comment by lacherp** [comment]
ok replace round arrow with class_obj icon

**Comment by lacherp** [comment]
ok replace round arrow with class_obj icon
