### ISSUE TITLE
AdapterSpy : make sure that this spy is a pure E4 plugin

### ISSUE THREAD

**Issue by opcoach** [lacherp/org.eclipse.e4.tools#9]
The new spies should be as much as possible defined as pure e4 plugins. For the moment it is not the case. 

You should : 

- remove the dependency to org.eclipse.ui
- remove the Activator (useless because no code inside and inherits from an E3 class)
- ensure to use injected 'Adapter' instance (containing all adapterFactories)
- ...

Other code seems to be ok (AdapterSpyPart is an E4 part for instance ... ).

**Comment by lacherp** [comment]
i use AdapterManager and IExtensionRegistry injected to get all needed informations
I think it's to be ok for me

**Comment by opcoach** [comment]
Yes no more dependency to org.eclipse.ui..  this plugin is a pure E4 plugin. Close
